[[redirects]]
  from = "/api/*"
  to = "http://rap2api.taobao.org/app/mock/118863"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
